// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo_msg.proto

#include "echo_msg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace sylar_rpc {
constexpr Echo_message::Echo_message(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : echo_message_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , header_(nullptr){}
struct Echo_messageDefaultTypeInternal {
  constexpr Echo_messageDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~Echo_messageDefaultTypeInternal() {}
  union {
    Echo_message _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT Echo_messageDefaultTypeInternal _Echo_message_default_instance_;
}  // namespace sylar_rpc
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_echo_5fmsg_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_echo_5fmsg_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_echo_5fmsg_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_echo_5fmsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sylar_rpc::Echo_message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sylar_rpc::Echo_message, header_),
  PROTOBUF_FIELD_OFFSET(::sylar_rpc::Echo_message, echo_message_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::sylar_rpc::Echo_message)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::sylar_rpc::_Echo_message_default_instance_),
};

const char descriptor_table_protodef_echo_5fmsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016echo_msg.proto\022\tsylar_rpc\032\014header.prot"
  "o\"G\n\014Echo_message\022!\n\006header\030\001 \001(\0132\021.syla"
  "r_rpc.Header\022\024\n\014echo_message\030\002 \001(\014b\006prot"
  "o3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_echo_5fmsg_2eproto_deps[1] = {
  &::descriptor_table_header_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_echo_5fmsg_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_echo_5fmsg_2eproto = {
  false, false, 122, descriptor_table_protodef_echo_5fmsg_2eproto, "echo_msg.proto", 
  &descriptor_table_echo_5fmsg_2eproto_once, descriptor_table_echo_5fmsg_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_echo_5fmsg_2eproto::offsets,
  file_level_metadata_echo_5fmsg_2eproto, file_level_enum_descriptors_echo_5fmsg_2eproto, file_level_service_descriptors_echo_5fmsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_echo_5fmsg_2eproto_getter() {
  return &descriptor_table_echo_5fmsg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_echo_5fmsg_2eproto(&descriptor_table_echo_5fmsg_2eproto);
namespace sylar_rpc {

// ===================================================================

class Echo_message::_Internal {
 public:
  static const ::sylar_rpc::Header& header(const Echo_message* msg);
};

const ::sylar_rpc::Header&
Echo_message::_Internal::header(const Echo_message* msg) {
  return *msg->header_;
}
void Echo_message::clear_header() {
  if (GetArenaForAllocation() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
}
Echo_message::Echo_message(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:sylar_rpc.Echo_message)
}
Echo_message::Echo_message(const Echo_message& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  echo_message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_echo_message().empty()) {
    echo_message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_echo_message(), 
      GetArenaForAllocation());
  }
  if (from._internal_has_header()) {
    header_ = new ::sylar_rpc::Header(*from.header_);
  } else {
    header_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:sylar_rpc.Echo_message)
}

void Echo_message::SharedCtor() {
echo_message_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
header_ = nullptr;
}

Echo_message::~Echo_message() {
  // @@protoc_insertion_point(destructor:sylar_rpc.Echo_message)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Echo_message::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  echo_message_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete header_;
}

void Echo_message::ArenaDtor(void* object) {
  Echo_message* _this = reinterpret_cast< Echo_message* >(object);
  (void)_this;
}
void Echo_message::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Echo_message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Echo_message::Clear() {
// @@protoc_insertion_point(message_clear_start:sylar_rpc.Echo_message)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  echo_message_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && header_ != nullptr) {
    delete header_;
  }
  header_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Echo_message::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .sylar_rpc.Header header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes echo_message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_echo_message();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Echo_message::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:sylar_rpc.Echo_message)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .sylar_rpc.Header header = 1;
  if (this->has_header()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::header(this), target, stream);
  }

  // bytes echo_message = 2;
  if (!this->echo_message().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_echo_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sylar_rpc.Echo_message)
  return target;
}

size_t Echo_message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sylar_rpc.Echo_message)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes echo_message = 2;
  if (!this->echo_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_echo_message());
  }

  // .sylar_rpc.Header header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *header_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Echo_message::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sylar_rpc.Echo_message)
  GOOGLE_DCHECK_NE(&from, this);
  const Echo_message* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Echo_message>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sylar_rpc.Echo_message)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sylar_rpc.Echo_message)
    MergeFrom(*source);
  }
}

void Echo_message::MergeFrom(const Echo_message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sylar_rpc.Echo_message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from.echo_message().empty()) {
    _internal_set_echo_message(from._internal_echo_message());
  }
  if (from.has_header()) {
    _internal_mutable_header()->::sylar_rpc::Header::MergeFrom(from._internal_header());
  }
}

void Echo_message::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sylar_rpc.Echo_message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Echo_message::CopyFrom(const Echo_message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sylar_rpc.Echo_message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Echo_message::IsInitialized() const {
  return true;
}

void Echo_message::InternalSwap(Echo_message* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &echo_message_, GetArenaForAllocation(),
      &other->echo_message_, other->GetArenaForAllocation()
  );
  swap(header_, other->header_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Echo_message::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_echo_5fmsg_2eproto_getter, &descriptor_table_echo_5fmsg_2eproto_once,
      file_level_metadata_echo_5fmsg_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace sylar_rpc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::sylar_rpc::Echo_message* Arena::CreateMaybeMessage< ::sylar_rpc::Echo_message >(Arena* arena) {
  return Arena::CreateMessageInternal< ::sylar_rpc::Echo_message >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
