// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo_msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_echo_5fmsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_echo_5fmsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_echo_5fmsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_echo_5fmsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_echo_5fmsg_2eproto;
namespace sylar_rpc {
class Echo_message;
struct Echo_messageDefaultTypeInternal;
extern Echo_messageDefaultTypeInternal _Echo_message_default_instance_;
}  // namespace sylar_rpc
PROTOBUF_NAMESPACE_OPEN
template<> ::sylar_rpc::Echo_message* Arena::CreateMaybeMessage<::sylar_rpc::Echo_message>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace sylar_rpc {

// ===================================================================

class Echo_message final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:sylar_rpc.Echo_message) */ {
 public:
  inline Echo_message() : Echo_message(nullptr) {}
  ~Echo_message() override;
  explicit constexpr Echo_message(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Echo_message(const Echo_message& from);
  Echo_message(Echo_message&& from) noexcept
    : Echo_message() {
    *this = ::std::move(from);
  }

  inline Echo_message& operator=(const Echo_message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Echo_message& operator=(Echo_message&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Echo_message& default_instance() {
    return *internal_default_instance();
  }
  static inline const Echo_message* internal_default_instance() {
    return reinterpret_cast<const Echo_message*>(
               &_Echo_message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Echo_message& a, Echo_message& b) {
    a.Swap(&b);
  }
  inline void Swap(Echo_message* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Echo_message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Echo_message* New() const final {
    return new Echo_message();
  }

  Echo_message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Echo_message>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Echo_message& from);
  void MergeFrom(const Echo_message& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Echo_message* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "sylar_rpc.Echo_message";
  }
  protected:
  explicit Echo_message(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEchoMessageFieldNumber = 2,
    kHeaderFieldNumber = 1,
  };
  // bytes echo_message = 2;
  void clear_echo_message();
  const std::string& echo_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_echo_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_echo_message();
  PROTOBUF_FUTURE_MUST_USE_RESULT std::string* release_echo_message();
  void set_allocated_echo_message(std::string* echo_message);
  private:
  const std::string& _internal_echo_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_echo_message(const std::string& value);
  std::string* _internal_mutable_echo_message();
  public:

  // .sylar_rpc.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::sylar_rpc::Header& header() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::sylar_rpc::Header* release_header();
  ::sylar_rpc::Header* mutable_header();
  void set_allocated_header(::sylar_rpc::Header* header);
  private:
  const ::sylar_rpc::Header& _internal_header() const;
  ::sylar_rpc::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::sylar_rpc::Header* header);
  ::sylar_rpc::Header* unsafe_arena_release_header();

  // @@protoc_insertion_point(class_scope:sylar_rpc.Echo_message)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr echo_message_;
  ::sylar_rpc::Header* header_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_echo_5fmsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Echo_message

// .sylar_rpc.Header header = 1;
inline bool Echo_message::_internal_has_header() const {
  return this != internal_default_instance() && header_ != nullptr;
}
inline bool Echo_message::has_header() const {
  return _internal_has_header();
}
inline const ::sylar_rpc::Header& Echo_message::_internal_header() const {
  const ::sylar_rpc::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::sylar_rpc::Header&>(
      ::sylar_rpc::_Header_default_instance_);
}
inline const ::sylar_rpc::Header& Echo_message::header() const {
  // @@protoc_insertion_point(field_get:sylar_rpc.Echo_message.header)
  return _internal_header();
}
inline void Echo_message::unsafe_arena_set_allocated_header(
    ::sylar_rpc::Header* header) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:sylar_rpc.Echo_message.header)
}
inline ::sylar_rpc::Header* Echo_message::release_header() {
  
  ::sylar_rpc::Header* temp = header_;
  header_ = nullptr;
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::sylar_rpc::Header* Echo_message::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:sylar_rpc.Echo_message.header)
  
  ::sylar_rpc::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::sylar_rpc::Header* Echo_message::_internal_mutable_header() {
  
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::sylar_rpc::Header>(GetArenaForAllocation());
    header_ = p;
  }
  return header_;
}
inline ::sylar_rpc::Header* Echo_message::mutable_header() {
  // @@protoc_insertion_point(field_mutable:sylar_rpc.Echo_message.header)
  return _internal_mutable_header();
}
inline void Echo_message::set_allocated_header(::sylar_rpc::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header));
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:sylar_rpc.Echo_message.header)
}

// bytes echo_message = 2;
inline void Echo_message::clear_echo_message() {
  echo_message_.ClearToEmpty();
}
inline const std::string& Echo_message::echo_message() const {
  // @@protoc_insertion_point(field_get:sylar_rpc.Echo_message.echo_message)
  return _internal_echo_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Echo_message::set_echo_message(ArgT0&& arg0, ArgT... args) {
 
 echo_message_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:sylar_rpc.Echo_message.echo_message)
}
inline std::string* Echo_message::mutable_echo_message() {
  // @@protoc_insertion_point(field_mutable:sylar_rpc.Echo_message.echo_message)
  return _internal_mutable_echo_message();
}
inline const std::string& Echo_message::_internal_echo_message() const {
  return echo_message_.Get();
}
inline void Echo_message::_internal_set_echo_message(const std::string& value) {
  
  echo_message_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Echo_message::_internal_mutable_echo_message() {
  
  return echo_message_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Echo_message::release_echo_message() {
  // @@protoc_insertion_point(field_release:sylar_rpc.Echo_message.echo_message)
  return echo_message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void Echo_message::set_allocated_echo_message(std::string* echo_message) {
  if (echo_message != nullptr) {
    
  } else {
    
  }
  echo_message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), echo_message,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:sylar_rpc.Echo_message.echo_message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace sylar_rpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_echo_5fmsg_2eproto
